#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.
#
# Government of Canada Cloud Guardrails Extensions
# Eric Maia and Scott Levac Treasury Board of Canada Secretariat
# December 2019
# Looks for passwords under 12 characters in length. Note, this check is a copy of 
# the CIS check that looks for 14 character password policy, however the GC recommedns 12
CHECK_ID_extragc32="3.2"
CHECK_TITLE_extragc32="[checkGC32] Ensure IAM password policy requires minimum length of 12 or greater (GC Password Guidance)"
CHECK_SCORED_extragc32="NOT_SCORED"
CHECK_TYPE_extragc32="EXTRA"
CHECK_ALTERNATE_extragc32="extragc32"

extragc32(){
  # "Ensure IAM password policy requires minimum length of 12 or greater (Scored)"
  COMMANDGC32=$($AWSCLI iam get-account-password-policy $PROFILE_OPT --region $REGION --output json --query 'PasswordPolicy.MinimumPasswordLength' 2> /dev/null)
  if [[ $COMMANDGC32 -gt "11" ]];then
    textPass "Password Policy requires more than 11 characters"
  else
    textFail "Password Policy missing or weak length requirement"
  fi
}
