#!/usr/bin/env bash
# Prowler - the handy cloud security tool (copyright 2019) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Remediation:
#
#   here URL to the relevand/official documentation
#
#   here commands or steps to fix it if avalable, like: 
#   aws logs put-metric-filter \
#     --region us-east-1 \
#     --log-group-name CloudTrail/MyCloudTrailLG \
#     --filter-name AWSCloudTrailChanges \
#     --filter-pattern '{ ($.eventName = CreateTrail) || ($.eventName = UpdateTrail) || ($.eventName = DeleteTrail) || ($.eventName = StartLogging) || ($.eventName = StopLogging) }' \
#     --metric-transformations metricName=CloudTrailEventCount,metricNamespace=CloudTrailMetrics,metricValue=1
#
#
# Government of Canada Cloud Guardrails Extensions
# Eric Maia and Scott Levac Treasury Board of Canada Secretariat
# December 2019
# Looks for the cloud SSC-CloudBroker role

CHECK_ID_extragc62="6.2"
CHECK_TITLE_extragc62="[checkGC61] Look for SSC_CloudBroker role (Not Scored) (part of GC Guardrails)"
CHECK_SCORED_extragc62="NOT_SCORED"
CHECK_TYPE_extragc62="EXTRA"
CHECK_ALTERNATE_extragc62="extragc62"




extragc62(){

SSC_REQ_POLICY_GC62="SSC-CloudBroker"

GC_SEC_POLICY_LIST=$($AWSCLI iam list-roles $PROFILE_OPT --region $REGION --output text --query 'Roles[*].RoleName')

    if [[ $GC_SEC_POLICY_LIST ]];then
      

      for policies in $GC_SEC_POLICY_LIST;do
       if [[ $policies == $SSC_REQ_POLICY_GC62 ]];then
           textPass "SSC required policy found"
           return
        fi
      done  
      textFail "Required SSC policy not found"
    else
      textFail "No policies can be found"
    fi
   
}
